const PYODIDE_VERSION = "314.0.3";
const PYODIDE_BASE = `https://cdn.jsdelivr.net/pyodide/v${PYODIDE_VERSION}/full/`;
const DATA_FILES = ["experiment.csv", "experiment_missing.csv", "projectile.csv"];

let pyodide = null;
let initializing = null;

function status(message, detail = "") {
  self.postMessage({ type: "status", message, detail });
}

async function writeBundledData() {
  for (const filename of DATA_FILES) {
    const url = new URL(`../data/${filename}`, self.location.href);
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`同梱データ ${filename} を読み込めませんでした (${response.status})`);
    }
    const bytes = new Uint8Array(await response.arrayBuffer());
    pyodide.FS.writeFile(`/home/pyodide/${filename}`, bytes);
  }
  pyodide.runPython("import os; os.chdir('/home/pyodide')");
}

async function initialize() {
  if (pyodide) return pyodide;
  if (initializing) return initializing;

  initializing = (async () => {
    status("Python実行環境を初期化しています", `Pyodide ${PYODIDE_VERSION}`);
    const { loadPyodide } = await import(`${PYODIDE_BASE}pyodide.mjs`);
    pyodide = await loadPyodide({ indexURL: PYODIDE_BASE });
    await writeBundledData();
    status("Python実行環境の準備ができました", `Python ${pyodide.runPython("import sys; sys.version.split()[0]")}`);
    self.postMessage({ type: "ready", pyodideVersion: PYODIDE_VERSION });
    return pyodide;
  })().catch((error) => {
    initializing = null;
    pyodide = null;
    throw error;
  });

  return initializing;
}

const EXECUTION_WRAPPER = String.raw`
import sys, os, io, json, base64, traceback, types, math, time, warnings, builtins
from contextlib import redirect_stdout, redirect_stderr

_student_code = __spica_student_code
_filename = __spica_filename
_initial_files = {"experiment.csv", "experiment_missing.csv", "projectile.csv"}

# Remove files generated by a previous run so every execution starts from the same bundled dataset.
for _existing_name in list(os.listdir("/home/pyodide")):
    _existing_path = os.path.join("/home/pyodide", _existing_name)
    if _existing_name not in _initial_files and os.path.isfile(_existing_path):
        try:
            os.remove(_existing_path)
        except OSError:
            pass

_stdout = io.StringIO()
_stderr = io.StringIO()
_figures = []
_files = []
_error = None
_started = time.perf_counter()

class _InputDisabledError(RuntimeError):
    pass

def _input_disabled(*args, **kwargs):
    raise _InputDisabledError(
        "このブラウザ教材では input() を使用しません。コード内の変数へ値を代入してから実行してください。"
    )

_user_builtins = dict(vars(builtins))
_user_builtins["input"] = _input_disabled
_user_globals = {"__name__": "__main__", "__builtins__": _user_builtins}


def _safe_number(value):
    try:
        if isinstance(value, bool):
            return value
        if isinstance(value, int):
            return value if abs(value) < 10**50 else str(value)
        if isinstance(value, float):
            if math.isnan(value):
                return "nan"
            if math.isinf(value):
                return "inf" if value > 0 else "-inf"
            return value
    except Exception:
        pass
    return None


def _sanitize(value, depth=0):
    if depth > 2:
        return {"type": type(value).__name__, "preview": "…"}
    if value is None or isinstance(value, (bool, int, float, str)):
        number = _safe_number(value)
        if number is not None or value is None or isinstance(value, (bool, int, float)):
            return {"type": type(value).__name__, "value": number}
        text = value if len(value) <= 300 else value[:297] + "…"
        return {"type": "str", "value": text, "length": len(value)}
    if isinstance(value, complex):
        return {"type": "complex", "value": str(value)}
    if isinstance(value, (list, tuple, set)):
        items = list(value)
        return {
            "type": type(value).__name__,
            "length": len(items),
            "preview": [_sanitize(item, depth + 1) for item in items[:12]],
        }
    if isinstance(value, dict):
        items = list(value.items())
        return {
            "type": "dict",
            "length": len(items),
            "preview": [
                {"key": str(key)[:80], "value": _sanitize(item, depth + 1)}
                for key, item in items[:12]
            ],
        }
    module_name = type(value).__module__
    if module_name.startswith("numpy"):
        try:
            import numpy as np
            arr = np.asarray(value)
            result = {
                "type": type(value).__name__,
                "shape": list(arr.shape),
                "dtype": str(arr.dtype),
                "size": int(arr.size),
                "preview": arr.reshape(-1)[:12].tolist(),
            }
            if arr.size and np.issubdtype(arr.dtype, np.number):
                finite = arr[np.isfinite(arr)] if np.issubdtype(arr.dtype, np.inexact) else arr
                if finite.size:
                    result["min"] = _safe_number(float(np.min(finite)))
                    result["max"] = _safe_number(float(np.max(finite)))
                    result["mean"] = _safe_number(float(np.mean(finite)))
            return result
        except Exception as exc:
            return {"type": type(value).__name__, "preview": f"<表示できません: {exc}>"}
    if isinstance(value, types.ModuleType):
        return None
    if isinstance(value, (types.FunctionType, type)):
        return {"type": type(value).__name__, "value": getattr(value, "__name__", str(value))}
    text = repr(value)
    return {"type": type(value).__name__, "preview": text[:300] + ("…" if len(text) > 300 else "")}

try:
    if "matplotlib" in _student_code:
        import matplotlib
        matplotlib.use("Agg")
    with warnings.catch_warnings(record=True) as _caught_warnings:
        warnings.simplefilter("always")
        with redirect_stdout(_stdout), redirect_stderr(_stderr):
            exec(compile(_student_code, _filename, "exec"), _user_globals, _user_globals)
        if _caught_warnings:
            for warning in _caught_warnings:
                _stderr.write(f"Warning: {warning.message}\n")
except BaseException:
    _error = traceback.format_exc()

# Capture matplotlib figures even when the program raised after creating one.
try:
    if "matplotlib.pyplot" in sys.modules:
        import matplotlib.pyplot as plt
        for _number in plt.get_fignums():
            _figure = plt.figure(_number)
            _buffer = io.BytesIO()
            _figure.savefig(_buffer, format="png", dpi=130, bbox_inches="tight")
            _figures.append(base64.b64encode(_buffer.getvalue()).decode("ascii"))
        plt.close("all")
except Exception as _figure_error:
    _stderr.write(f"Figure capture warning: {_figure_error}\n")

_variables = {}
for _name, _value in sorted(_user_globals.items()):
    if _name.startswith("_"):
        continue
    try:
        _serialized = _sanitize(_value)
        if _serialized is not None:
            _variables[_name] = _serialized
    except Exception:
        pass

# Return newly generated small files so the UI can offer downloads.
try:
    for _name in sorted(os.listdir("/home/pyodide")):
        _path = os.path.join("/home/pyodide", _name)
        if _name in _initial_files or not os.path.isfile(_path):
            continue
        _size = os.path.getsize(_path)
        if _size > 2_000_000:
            _files.append({"name": _name, "size": _size, "tooLarge": True})
            continue
        with open(_path, "rb") as _handle:
            _encoded = base64.b64encode(_handle.read()).decode("ascii")
        _files.append({"name": _name, "size": _size, "base64": _encoded})
except Exception as _file_error:
    _stderr.write(f"File collection warning: {_file_error}\n")

_elapsed_ms = (time.perf_counter() - _started) * 1000
_result = {
    "stdout": _stdout.getvalue()[-200000:],
    "stderr": _stderr.getvalue()[-100000:],
    "error": _error,
    "figures": _figures,
    "variables": _variables,
    "files": _files,
    "elapsedMs": _elapsed_ms,
}
json.dumps(_result, ensure_ascii=False)
`;

async function runCode(message) {
  const runtime = await initialize();
  const code = String(message.code ?? "");
  const filename = String(message.filename ?? "student.py");

  if (code.length > 200_000) {
    throw new Error("コードが長すぎます。200,000文字以下にしてください。");
  }

  status("必要なPythonパッケージを確認しています");
  await runtime.loadPackagesFromImports(code);
  status("Pythonコードを実行しています");

  runtime.globals.set("__spica_student_code", code);
  runtime.globals.set("__spica_filename", filename);
  try {
    const resultText = await runtime.runPythonAsync(EXECUTION_WRAPPER, { filename: "spica_runner.py" });
    const result = JSON.parse(resultText);
    self.postMessage({ type: "result", requestId: message.requestId, result });
  } finally {
    try { runtime.globals.delete("__spica_student_code"); } catch (_) {}
    try { runtime.globals.delete("__spica_filename"); } catch (_) {}
  }
}

self.onmessage = async (event) => {
  const message = event.data ?? {};
  try {
    if (message.type === "init") {
      await initialize();
      return;
    }
    if (message.type === "run") {
      await runCode(message);
      return;
    }
    if (message.type === "ping") {
      self.postMessage({ type: "pong", ready: Boolean(pyodide), pyodideVersion: PYODIDE_VERSION });
    }
  } catch (error) {
    self.postMessage({
      type: "worker-error",
      requestId: message.requestId,
      message: error?.message || String(error),
      stack: error?.stack || "",
    });
  }
};
